name: sertidemi
version: 1.0.1+2
publish_to: none
description: A new Flutter project.
environment: 
  sdk: '>=2.17.0 <3.0.0'

dependencies: 
  cupertino_icons: ^1.0.2
  get: 4.6.3
  flutter: 
    sdk: flutter
  google_fonts: ^2.3.3
  flutter_gen_runner: ^4.2.1
  image_picker: ^0.8.5+3
  http: ^0.13.4
  loading_animation_widget: ^1.2.0+1
  get_storage: ^2.0.3
  intl: ^0.17.0
  cached_network_image: ^3.2.1
  share_plus: ^4.0.9
  path_provider: ^2.0.11
  slide_countdown: ^0.2.8
  path: ^1.8.1
  url_launcher: ^6.1.4
  dio: ^4.0.6
  permission_handler: ^10.0.0
  shimmer: ^2.0.0
  syncfusion_flutter_pdfviewer: ^20.1.57-beta
  package_info_plus: ^1.4.2

dev_dependencies: 
  flutter_lints: ^2.0.0
  flutter_gen_runner:
  flutter_test: 
    sdk: flutter

flutter: 
  uses-material-design: true

  assets:
    - assets/images/
    - assets/icons/

  